/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta25 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta25
     */
    public Pregunta25() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p25 = new javax.swing.ButtonGroup();
        p25rb1 = new javax.swing.JRadioButton();
        p25rb2 = new javax.swing.JRadioButton();
        p25rb3 = new javax.swing.JRadioButton();
        p25rb4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));

        g1p25.add(p25rb1);
        p25rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p25rb1.setForeground(new java.awt.Color(255, 255, 255));
        p25rb1.setText("Nunca");
        p25rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p25rb1.setOpaque(false);
        p25rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p25rb1ActionPerformed(evt);
            }
        });

        g1p25.add(p25rb2);
        p25rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p25rb2.setForeground(new java.awt.Color(255, 255, 255));
        p25rb2.setText("Una vez");
        p25rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p25rb2.setOpaque(false);

        g1p25.add(p25rb3);
        p25rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p25rb3.setForeground(new java.awt.Color(255, 255, 255));
        p25rb3.setText("Algunas veces");
        p25rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p25rb3.setOpaque(false);

        g1p25.add(p25rb4);
        p25rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p25rb4.setForeground(new java.awt.Color(255, 255, 255));
        p25rb4.setText("Varias veces");
        p25rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p25rb4.setOpaque(false);
        p25rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p25rb4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("25. ¿Cuándo estas tranquilo te han dado sensaciones ");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("de nauseas, mareo, vómito?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p25rb1)
                    .addComponent(p25rb2)
                    .addComponent(p25rb3)
                    .addComponent(p25rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(p25rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p25rb2)
                .addGap(5, 5, 5)
                .addComponent(p25rb3)
                .addGap(5, 5, 5)
                .addComponent(p25rb4)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p25rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p25rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p25rb1ActionPerformed

    private void p25rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p25rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p25rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p25rb1;
    public javax.swing.JRadioButton p25rb2;
    public javax.swing.JRadioButton p25rb3;
    public javax.swing.JRadioButton p25rb4;
    // End of variables declaration//GEN-END:variables
}
