/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta2 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta2
     */
    public Pregunta2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        g1p2 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        p2rb1 = new javax.swing.JRadioButton();
        p2rb2 = new javax.swing.JRadioButton();
        p2rb3 = new javax.swing.JRadioButton();
        p2rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2.¿Cuánto te mide el diámetro la cintura?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 57, 0, 42);
        add(jLabel7, gridBagConstraints);

        g1p2.add(p2rb1);
        p2rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p2rb1.setForeground(new java.awt.Color(255, 255, 255));
        p2rb1.setText("Menos de 70 cm");
        p2rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p2rb1.setOpaque(false);
        p2rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2rb1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 110, 0, 0);
        add(p2rb1, gridBagConstraints);

        g1p2.add(p2rb2);
        p2rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p2rb2.setForeground(new java.awt.Color(255, 255, 255));
        p2rb2.setText("Entre 71 y 80 cm");
        p2rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p2rb2.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 110, 0, 0);
        add(p2rb2, gridBagConstraints);

        g1p2.add(p2rb3);
        p2rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p2rb3.setForeground(new java.awt.Color(255, 255, 255));
        p2rb3.setText("Entre 80 y 90 cm");
        p2rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p2rb3.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 110, 0, 0);
        add(p2rb3, gridBagConstraints);

        g1p2.add(p2rb4);
        p2rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p2rb4.setForeground(new java.awt.Color(255, 255, 255));
        p2rb4.setText("Mas de 90 cm");
        p2rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p2rb4.setOpaque(false);
        p2rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2rb4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 110, 28, 0);
        add(p2rb4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void p2rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2rb1ActionPerformed

    private void p2rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p2;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p2rb1;
    public javax.swing.JRadioButton p2rb2;
    public javax.swing.JRadioButton p2rb3;
    public javax.swing.JRadioButton p2rb4;
    // End of variables declaration//GEN-END:variables
}
