/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta23 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta23
     */
    public Pregunta23() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p23 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p23rb1 = new javax.swing.JRadioButton();
        p23rb2 = new javax.swing.JRadioButton();
        p23rb3 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("23. ¿Cuántas porciones de frutas y verduras comes en un día típico?");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Basa tus respuestas en tus hábitos alimenticios del mes pasado. ");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nota: Una porción es aproximadamente del tamaño de una manzana.");

        g1p23.add(p23rb1);
        p23rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p23rb1.setForeground(new java.awt.Color(255, 255, 255));
        p23rb1.setText("5 o más porciones");
        p23rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p23rb1.setOpaque(false);
        p23rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p23rb1ActionPerformed(evt);
            }
        });

        g1p23.add(p23rb2);
        p23rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p23rb2.setForeground(new java.awt.Color(255, 255, 255));
        p23rb2.setText("2 a 4 porciones");
        p23rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p23rb2.setOpaque(false);
        p23rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p23rb2ActionPerformed(evt);
            }
        });

        g1p23.add(p23rb3);
        p23rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p23rb3.setForeground(new java.awt.Color(255, 255, 255));
        p23rb3.setText("0 a 1 porción");
        p23rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p23rb3.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p23rb1)
                    .addComponent(p23rb2)
                    .addComponent(p23rb3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(p23rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p23rb2)
                .addGap(5, 5, 5)
                .addComponent(p23rb3)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p23rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p23rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p23rb1ActionPerformed

    private void p23rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p23rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p23rb2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JRadioButton p23rb1;
    public javax.swing.JRadioButton p23rb2;
    public javax.swing.JRadioButton p23rb3;
    // End of variables declaration//GEN-END:variables
}
