/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta15 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta2
     */
    public Pregunta15() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p15 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        p15rb1 = new javax.swing.JRadioButton();
        p15rb2 = new javax.swing.JRadioButton();
        p15rb3 = new javax.swing.JRadioButton();
        p15rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("15.¿Te estresas cuando estas en casa?");

        g1p15.add(p15rb1);
        p15rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p15rb1.setForeground(new java.awt.Color(255, 255, 255));
        p15rb1.setText("No me estreso");
        p15rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p15rb1.setOpaque(false);
        p15rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p15rb1ActionPerformed(evt);
            }
        });

        g1p15.add(p15rb2);
        p15rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p15rb2.setForeground(new java.awt.Color(255, 255, 255));
        p15rb2.setText("Cuando estoy sometido a presiones");
        p15rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p15rb2.setOpaque(false);

        g1p15.add(p15rb3);
        p15rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p15rb3.setForeground(new java.awt.Color(255, 255, 255));
        p15rb3.setText("Con frecuencia");
        p15rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p15rb3.setOpaque(false);

        g1p15.add(p15rb4);
        p15rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p15rb4.setForeground(new java.awt.Color(255, 255, 255));
        p15rb4.setText("Me estreso continuamente");
        p15rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p15rb4.setOpaque(false);
        p15rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p15rb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p15rb1)
                            .addComponent(p15rb2)
                            .addComponent(p15rb3)
                            .addComponent(p15rb4))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p15rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p15rb2)
                .addGap(5, 5, 5)
                .addComponent(p15rb3)
                .addGap(5, 5, 5)
                .addComponent(p15rb4)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p15rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p15rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p15rb1ActionPerformed

    private void p15rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p15rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p15rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p15;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p15rb1;
    public javax.swing.JRadioButton p15rb2;
    public javax.swing.JRadioButton p15rb3;
    public javax.swing.JRadioButton p15rb4;
    // End of variables declaration//GEN-END:variables
}
