/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta12 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p12 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p12rb1 = new javax.swing.JRadioButton();
        p12rb2 = new javax.swing.JRadioButton();
        p12rb3 = new javax.swing.JRadioButton();
        p12rb4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("12.Cuando haces esfuerzo físico o tienes estres ¿sientes dolor  ");

        g1p12.add(p12rb1);
        p12rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p12rb1.setForeground(new java.awt.Color(255, 255, 255));
        p12rb1.setText("No");
        p12rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p12rb1.setOpaque(false);
        p12rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12rb1ActionPerformed(evt);
            }
        });

        g1p12.add(p12rb2);
        p12rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p12rb2.setForeground(new java.awt.Color(255, 255, 255));
        p12rb2.setText("Si, cuando hago esfuerzos físicos");
        p12rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p12rb2.setOpaque(false);
        p12rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12rb2ActionPerformed(evt);
            }
        });

        g1p12.add(p12rb3);
        p12rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p12rb3.setForeground(new java.awt.Color(255, 255, 255));
        p12rb3.setText("Si, cuando tengo estrés");
        p12rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p12rb3.setOpaque(false);

        g1p12.add(p12rb4);
        p12rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p12rb4.setForeground(new java.awt.Color(255, 255, 255));
        p12rb4.setText("Si, cuando hago esfuerzos físicos y cuando tengo estrés. ");
        p12rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p12rb4.setOpaque(false);
        p12rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p12rb4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("o molestiasmolestias (por ejemplo, hormigueo, ");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("entumecimiento o ardor)en el pecho?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p12rb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p12rb1)
                            .addComponent(p12rb2)
                            .addComponent(p12rb3))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p12rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p12rb2)
                .addGap(5, 5, 5)
                .addComponent(p12rb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p12rb4)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p12rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p12rb1ActionPerformed

    private void p12rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p12rb4ActionPerformed

    private void p12rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p12rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p12rb2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JRadioButton p12rb1;
    public javax.swing.JRadioButton p12rb2;
    public javax.swing.JRadioButton p12rb3;
    public javax.swing.JRadioButton p12rb4;
    // End of variables declaration//GEN-END:variables
}
