/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta1 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p1rb4 = new javax.swing.JRadioButton();
        p1rb3 = new javax.swing.JRadioButton();
        p1rb2 = new javax.swing.JRadioButton();
        p1rb1 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1. ¿Qué edad tienes?");
        add(jLabel6);
        jLabel6.setBounds(121, 30, 221, 29);

        g1p1.add(p1rb4);
        p1rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p1rb4.setForeground(new java.awt.Color(255, 255, 255));
        p1rb4.setText("Menos de 45 años");
        p1rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p1rb4.setOpaque(false);
        add(p1rb4);
        p1rb4.setBounds(91, 100, 165, 30);

        g1p1.add(p1rb3);
        p1rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p1rb3.setForeground(new java.awt.Color(255, 255, 255));
        p1rb3.setText("Entre 46 y 55 años");
        p1rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p1rb3.setOpaque(false);
        add(p1rb3);
        p1rb3.setBounds(91, 130, 171, 29);

        g1p1.add(p1rb2);
        p1rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p1rb2.setForeground(new java.awt.Color(255, 255, 255));
        p1rb2.setText("Entre 56 y 65 años");
        p1rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p1rb2.setOpaque(false);
        add(p1rb2);
        p1rb2.setBounds(91, 160, 171, 29);

        g1p1.add(p1rb1);
        p1rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p1rb1.setForeground(new java.awt.Color(255, 255, 255));
        p1rb1.setText("Más de 66 años");
        p1rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p1rb1.setOpaque(false);
        p1rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1rb1ActionPerformed(evt);
            }
        });
        add(p1rb1);
        p1rb1.setBounds(91, 190, 143, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void p1rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1rb1ActionPerformed
        
    }//GEN-LAST:event_p1rb1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup g1p1;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton p1rb1;
    public javax.swing.JRadioButton p1rb2;
    public javax.swing.JRadioButton p1rb3;
    public javax.swing.JRadioButton p1rb4;
    // End of variables declaration//GEN-END:variables
}

