/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta8 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p8 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p8rb1 = new javax.swing.JRadioButton();
        p8rb2 = new javax.swing.JRadioButton();
        p8rb3 = new javax.swing.JRadioButton();
        p8rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("8.¿Cuál es tu nivel de tensión arterial?");

        g1p8.add(p8rb1);
        p8rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p8rb1.setForeground(new java.awt.Color(255, 255, 255));
        p8rb1.setText("Menos de 120 mmHgg");
        p8rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p8rb1.setOpaque(false);
        p8rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8rb1ActionPerformed(evt);
            }
        });

        g1p8.add(p8rb2);
        p8rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p8rb2.setForeground(new java.awt.Color(255, 255, 255));
        p8rb2.setText("Entre 120 y 140 mmHg");
        p8rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p8rb2.setOpaque(false);
        p8rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8rb2ActionPerformed(evt);
            }
        });

        g1p8.add(p8rb3);
        p8rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p8rb3.setForeground(new java.awt.Color(255, 255, 255));
        p8rb3.setText("Entre 140 y 160 mmHg");
        p8rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p8rb3.setOpaque(false);
        p8rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8rb3ActionPerformed(evt);
            }
        });

        g1p8.add(p8rb4);
        p8rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p8rb4.setForeground(new java.awt.Color(255, 255, 255));
        p8rb4.setText("Mas de 160 mmH");
        p8rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p8rb4.setOpaque(false);
        p8rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8rb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p8rb1)
                    .addComponent(p8rb2)
                    .addComponent(p8rb3)
                    .addComponent(p8rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p8rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p8rb2)
                .addGap(5, 5, 5)
                .addComponent(p8rb3)
                .addGap(5, 5, 5)
                .addComponent(p8rb4)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p8rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p8rb1ActionPerformed

    private void p8rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p8rb4ActionPerformed

    private void p8rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p8rb2ActionPerformed

    private void p8rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p8rb3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p8;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton p8rb1;
    public javax.swing.JRadioButton p8rb2;
    public javax.swing.JRadioButton p8rb3;
    public javax.swing.JRadioButton p8rb4;
    // End of variables declaration//GEN-END:variables
}
