/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta21 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta21
     */
    public Pregunta21() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        g1p21 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        p21rb1 = new javax.swing.JRadioButton();
        p21rb2 = new javax.swing.JRadioButton();
        p21rb3 = new javax.swing.JRadioButton();
        p21rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));
        setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("21. ¿Sientes que comes para calmar los nervios?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 57, 0, 42);
        add(jLabel7, gridBagConstraints);

        g1p21.add(p21rb1);
        p21rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p21rb1.setForeground(new java.awt.Color(255, 255, 255));
        p21rb1.setText("Varias veces");
        p21rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p21rb1.setOpaque(false);
        p21rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p21rb1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 110, 0, 0);
        add(p21rb1, gridBagConstraints);

        g1p21.add(p21rb2);
        p21rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p21rb2.setForeground(new java.awt.Color(255, 255, 255));
        p21rb2.setText("Alguna vez");
        p21rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p21rb2.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 110, 0, 0);
        add(p21rb2, gridBagConstraints);

        g1p21.add(p21rb3);
        p21rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p21rb3.setForeground(new java.awt.Color(255, 255, 255));
        p21rb3.setText("Una vez");
        p21rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p21rb3.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 110, 0, 0);
        add(p21rb3, gridBagConstraints);

        g1p21.add(p21rb4);
        p21rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p21rb4.setForeground(new java.awt.Color(255, 255, 255));
        p21rb4.setText("Casi nunca");
        p21rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p21rb4.setOpaque(false);
        p21rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p21rb4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 110, 28, 0);
        add(p21rb4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void p21rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p21rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p21rb1ActionPerformed

    private void p21rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p21rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p21rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p21;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p21rb1;
    public javax.swing.JRadioButton p21rb2;
    public javax.swing.JRadioButton p21rb3;
    public javax.swing.JRadioButton p21rb4;
    // End of variables declaration//GEN-END:variables
}
