/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta3 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p3 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p3rb1 = new javax.swing.JRadioButton();
        p3rb2 = new javax.swing.JRadioButton();
        p3rb3 = new javax.swing.JRadioButton();
        p3rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("3.Tu trabajo te obliga a estar constantemente ");
        add(jLabel6);
        jLabel6.setBounds(30, 20, 520, 41);

        g1p3.add(p3rb1);
        p3rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p3rb1.setForeground(new java.awt.Color(255, 255, 255));
        p3rb1.setText("Sentado");
        p3rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p3rb1.setOpaque(false);
        p3rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3rb1ActionPerformed(evt);
            }
        });
        add(p3rb1);
        p3rb1.setBounds(70, 90, 91, 29);

        g1p3.add(p3rb2);
        p3rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p3rb2.setForeground(new java.awt.Color(255, 255, 255));
        p3rb2.setText("De pie");
        p3rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p3rb2.setOpaque(false);
        add(p3rb2);
        p3rb2.setBounds(70, 120, 77, 29);

        g1p3.add(p3rb3);
        p3rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p3rb3.setForeground(new java.awt.Color(255, 255, 255));
        p3rb3.setText("En movimiento");
        p3rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p3rb3.setOpaque(false);
        p3rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3rb3ActionPerformed(evt);
            }
        });
        add(p3rb3);
        p3rb3.setBounds(70, 150, 145, 29);

        g1p3.add(p3rb4);
        p3rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p3rb4.setForeground(new java.awt.Color(255, 255, 255));
        p3rb4.setText("En deporte");
        p3rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p3rb4.setOpaque(false);
        p3rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3rb4ActionPerformed(evt);
            }
        });
        add(p3rb4);
        p3rb4.setBounds(70, 180, 115, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void p3rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3rb1ActionPerformed

    private void p3rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3rb4ActionPerformed

    private void p3rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p3rb3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p3;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton p3rb1;
    public javax.swing.JRadioButton p3rb2;
    public javax.swing.JRadioButton p3rb3;
    public javax.swing.JRadioButton p3rb4;
    // End of variables declaration//GEN-END:variables
}
