/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta16 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta16
     */
    public Pregunta16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p16 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        p16rb1 = new javax.swing.JRadioButton();
        p16rb2 = new javax.swing.JRadioButton();
        p16rb3 = new javax.swing.JRadioButton();
        p16rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("16. ¿Te estresas cuando estas en tu lugar de trabajo?");

        g1p16.add(p16rb1);
        p16rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p16rb1.setForeground(new java.awt.Color(255, 255, 255));
        p16rb1.setText("No me estreso");
        p16rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p16rb1.setOpaque(false);
        p16rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p16rb1ActionPerformed(evt);
            }
        });

        g1p16.add(p16rb2);
        p16rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p16rb2.setForeground(new java.awt.Color(255, 255, 255));
        p16rb2.setText("Cuando estoy sometido a presiones");
        p16rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p16rb2.setOpaque(false);

        g1p16.add(p16rb3);
        p16rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p16rb3.setForeground(new java.awt.Color(255, 255, 255));
        p16rb3.setText("Con frecuencia");
        p16rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p16rb3.setOpaque(false);

        g1p16.add(p16rb4);
        p16rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p16rb4.setForeground(new java.awt.Color(255, 255, 255));
        p16rb4.setText("Me estreso continuamente");
        p16rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p16rb4.setOpaque(false);
        p16rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p16rb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p16rb1)
                    .addComponent(p16rb2)
                    .addComponent(p16rb3)
                    .addComponent(p16rb4))
                .addContainerGap(213, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p16rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p16rb2)
                .addGap(5, 5, 5)
                .addComponent(p16rb3)
                .addGap(5, 5, 5)
                .addComponent(p16rb4)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p16rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p16rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p16rb1ActionPerformed

    private void p16rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p16rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p16rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p16;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p16rb1;
    public javax.swing.JRadioButton p16rb2;
    public javax.swing.JRadioButton p16rb3;
    public javax.swing.JRadioButton p16rb4;
    // End of variables declaration//GEN-END:variables
}
