/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta17 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta17
     */
    public Pregunta17() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p17 = new javax.swing.ButtonGroup();
        p17rb1 = new javax.swing.JRadioButton();
        p17rb2 = new javax.swing.JRadioButton();
        p17rb3 = new javax.swing.JRadioButton();
        p17rb4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));

        g1p17.add(p17rb1);
        p17rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p17rb1.setForeground(new java.awt.Color(255, 255, 255));
        p17rb1.setText("Varias veces");
        p17rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p17rb1.setOpaque(false);
        p17rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p17rb1ActionPerformed(evt);
            }
        });

        g1p17.add(p17rb2);
        p17rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p17rb2.setForeground(new java.awt.Color(255, 255, 255));
        p17rb2.setText("Alguna vez");
        p17rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p17rb2.setOpaque(false);

        g1p17.add(p17rb3);
        p17rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p17rb3.setForeground(new java.awt.Color(255, 255, 255));
        p17rb3.setText("Una vez");
        p17rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p17rb3.setOpaque(false);

        g1p17.add(p17rb4);
        p17rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p17rb4.setForeground(new java.awt.Color(255, 255, 255));
        p17rb4.setText("Nunca");
        p17rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p17rb4.setOpaque(false);
        p17rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p17rb4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("17. ¿Has tenido frecuentemente dificultades para concentrarte por ");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("tener la mente ocupada en preocupaciones?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p17rb1)
                    .addComponent(p17rb2)
                    .addComponent(p17rb3)
                    .addComponent(p17rb4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p17rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p17rb2)
                .addGap(5, 5, 5)
                .addComponent(p17rb3)
                .addGap(5, 5, 5)
                .addComponent(p17rb4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p17rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p17rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p17rb1ActionPerformed

    private void p17rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p17rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p17rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p17rb1;
    public javax.swing.JRadioButton p17rb2;
    public javax.swing.JRadioButton p17rb3;
    public javax.swing.JRadioButton p17rb4;
    // End of variables declaration//GEN-END:variables
}
