/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta4 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p4 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p4rb1 = new javax.swing.JRadioButton();
        p4rb2 = new javax.swing.JRadioButton();
        p4rb3 = new javax.swing.JRadioButton();
        p4rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4.¿Existen casos de infarto en algún familiar cercano?");

        g1p4.add(p4rb1);
        p4rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p4rb1.setForeground(new java.awt.Color(255, 255, 255));
        p4rb1.setText("No");
        p4rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4rb1.setOpaque(false);
        p4rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4rb1ActionPerformed(evt);
            }
        });

        g1p4.add(p4rb2);
        p4rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p4rb2.setForeground(new java.awt.Color(255, 255, 255));
        p4rb2.setText("Si, cuando tenía entre 56 y 70 años");
        p4rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4rb2.setOpaque(false);

        g1p4.add(p4rb3);
        p4rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p4rb3.setForeground(new java.awt.Color(255, 255, 255));
        p4rb3.setText("Si, cuando tenía entre 41 y 55 años");
        p4rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4rb3.setOpaque(false);

        g1p4.add(p4rb4);
        p4rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p4rb4.setForeground(new java.awt.Color(255, 255, 255));
        p4rb4.setText("Si, antes de los 40 años");
        p4rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4rb4.setOpaque(false);
        p4rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4rb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p4rb1)
                    .addComponent(p4rb2)
                    .addComponent(p4rb3)
                    .addComponent(p4rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p4rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p4rb2)
                .addGap(5, 5, 5)
                .addComponent(p4rb3)
                .addGap(5, 5, 5)
                .addComponent(p4rb4)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p4rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4rb1ActionPerformed

    private void p4rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p4rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton p4rb1;
    public javax.swing.JRadioButton p4rb2;
    public javax.swing.JRadioButton p4rb3;
    public javax.swing.JRadioButton p4rb4;
    // End of variables declaration//GEN-END:variables
}
