/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta10 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p10 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p10rb1 = new javax.swing.JRadioButton();
        p10rb2 = new javax.swing.JRadioButton();
        p10rb3 = new javax.swing.JRadioButton();
        p10rb4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("10.¿Has sentido presión en el pecho ");

        g1p10.add(p10rb1);
        p10rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p10rb1.setForeground(new java.awt.Color(255, 255, 255));
        p10rb1.setText("Nunca");
        p10rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p10rb1.setOpaque(false);
        p10rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10rb1ActionPerformed(evt);
            }
        });

        g1p10.add(p10rb2);
        p10rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p10rb2.setForeground(new java.awt.Color(255, 255, 255));
        p10rb2.setText("Una vez");
        p10rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p10rb2.setOpaque(false);
        p10rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10rb2ActionPerformed(evt);
            }
        });

        g1p10.add(p10rb3);
        p10rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p10rb3.setForeground(new java.awt.Color(255, 255, 255));
        p10rb3.setText("Alguna vez");
        p10rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p10rb3.setOpaque(false);

        g1p10.add(p10rb4);
        p10rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p10rb4.setForeground(new java.awt.Color(255, 255, 255));
        p10rb4.setText("Varias veces");
        p10rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p10rb4.setOpaque(false);
        p10rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10rb4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("por mas de diez minutos?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p10rb1)
                    .addComponent(p10rb2)
                    .addComponent(p10rb3)
                    .addComponent(p10rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p10rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p10rb2)
                .addGap(5, 5, 5)
                .addComponent(p10rb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p10rb4)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p10rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10rb1ActionPerformed

    private void p10rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10rb4ActionPerformed

    private void p10rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p10rb2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p10rb1;
    public javax.swing.JRadioButton p10rb2;
    public javax.swing.JRadioButton p10rb3;
    public javax.swing.JRadioButton p10rb4;
    // End of variables declaration//GEN-END:variables
}
