/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta5 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p5 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p5rb1 = new javax.swing.JRadioButton();
        p5rb2 = new javax.swing.JRadioButton();
        p5rb3 = new javax.swing.JRadioButton();
        p5rb4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("5.¿Existen casos de ictus (derrame cerebral)");

        g1p5.add(p5rb1);
        p5rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p5rb1.setForeground(new java.awt.Color(255, 255, 255));
        p5rb1.setText("No");
        p5rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p5rb1.setOpaque(false);
        p5rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5rb1ActionPerformed(evt);
            }
        });

        g1p5.add(p5rb2);
        p5rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p5rb2.setForeground(new java.awt.Color(255, 255, 255));
        p5rb2.setText("Si, cuando tenía entre 56 y 70 años");
        p5rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p5rb2.setOpaque(false);

        g1p5.add(p5rb3);
        p5rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p5rb3.setForeground(new java.awt.Color(255, 255, 255));
        p5rb3.setText("Si, cuando tenía entre 41 y 55 años");
        p5rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p5rb3.setOpaque(false);

        g1p5.add(p5rb4);
        p5rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p5rb4.setForeground(new java.awt.Color(255, 255, 255));
        p5rb4.setText("Si, antes de los 41 años");
        p5rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p5rb4.setOpaque(false);
        p5rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5rb4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" en algún familiar cercano?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p5rb1)
                            .addComponent(p5rb2)
                            .addComponent(p5rb3)
                            .addComponent(p5rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p5rb2)
                .addGap(5, 5, 5)
                .addComponent(p5rb3)
                .addGap(5, 5, 5)
                .addComponent(p5rb4)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p5rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5rb1ActionPerformed

    private void p5rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p5rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p5rb1;
    public javax.swing.JRadioButton p5rb2;
    public javax.swing.JRadioButton p5rb3;
    public javax.swing.JRadioButton p5rb4;
    // End of variables declaration//GEN-END:variables
}
