/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta6 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p6 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        p6rb1 = new javax.swing.JRadioButton();
        p6rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6.¿Sufres Diabetes?");

        g1p6.add(p6rb1);
        p6rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p6rb1.setForeground(new java.awt.Color(255, 255, 255));
        p6rb1.setText("No");
        p6rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p6rb1.setOpaque(false);
        p6rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6rb1ActionPerformed(evt);
            }
        });

        g1p6.add(p6rb4);
        p6rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p6rb4.setForeground(new java.awt.Color(255, 255, 255));
        p6rb4.setText("Si");
        p6rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p6rb4.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p6rb1)
                    .addComponent(p6rb4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p6rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p6rb4)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p6rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p6rb1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p6;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton p6rb1;
    public javax.swing.JRadioButton p6rb4;
    // End of variables declaration//GEN-END:variables
}
