/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Jessica
 */
public class Pregunta20 extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta20
     */
    public Pregunta20() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1p20 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        p20rb1 = new javax.swing.JRadioButton();
        p20rb2 = new javax.swing.JRadioButton();
        p20rb3 = new javax.swing.JRadioButton();
        p20rb4 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setPreferredSize(new java.awt.Dimension(630, 230));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("20. ¿Sientes que tienes apetito?");

        g1p20.add(p20rb1);
        p20rb1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p20rb1.setForeground(new java.awt.Color(255, 255, 255));
        p20rb1.setText("A menudo");
        p20rb1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p20rb1.setOpaque(false);
        p20rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20rb1ActionPerformed(evt);
            }
        });

        g1p20.add(p20rb2);
        p20rb2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p20rb2.setForeground(new java.awt.Color(255, 255, 255));
        p20rb2.setText("Alguna vez");
        p20rb2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p20rb2.setOpaque(false);

        g1p20.add(p20rb3);
        p20rb3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p20rb3.setForeground(new java.awt.Color(255, 255, 255));
        p20rb3.setText("Una vez");
        p20rb3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p20rb3.setOpaque(false);

        g1p20.add(p20rb4);
        p20rb4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        p20rb4.setForeground(new java.awt.Color(255, 255, 255));
        p20rb4.setText("Casi nunca");
        p20rb4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p20rb4.setOpaque(false);
        p20rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p20rb4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p20rb1)
                            .addComponent(p20rb2)
                            .addComponent(p20rb3)
                            .addComponent(p20rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p20rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(p20rb2)
                .addGap(5, 5, 5)
                .addComponent(p20rb3)
                .addGap(5, 5, 5)
                .addComponent(p20rb4)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p20rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p20rb1ActionPerformed

    private void p20rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p20rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p20rb4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup g1p20;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JRadioButton p20rb1;
    public javax.swing.JRadioButton p20rb2;
    public javax.swing.JRadioButton p20rb3;
    public javax.swing.JRadioButton p20rb4;
    // End of variables declaration//GEN-END:variables
}
